In [2]:
#code to add column for day of year
import pandas as pd
import numpy as np
flights = pd.read_csv('flightsbyWW.csv')
flights = pd.DataFrame(flights)

In [3]:
flights.head()

,Unnamed: 0,index,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,...,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,WW
0,0,0,2015,1,1,4,AS,98,N407AS,ANC,...,-22.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1,1,2015,1,1,4,AA,2336,N3KUAA,LAX,...,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2,2,2015,1,1,4,US,840,N171US,SFO,...,5.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1
3,3,3,2015,1,1,4,AA,258,N3HYAA,LAX,...,-9.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1
4,4,4,2015,1,1,4,AS,135,N527AS,SEA,...,-21.0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,1

In [6]:
flights2 = flights[['DAY_OF_WEEK','AIRLINE', 'FLIGHT_NUMBER', 'TAIL_NUMBER', 'ORIGIN_AIRPORT', 'DESTINATION_AIRPORT', 'ARRIVAL_DELAY', 'AIR_SYSTEM_DELAY', 'SECURITY_DELAY', 'AIRLINE_DELAY', 'LATE_AIRCRAFT_DELAY', 'WEATHER_DELAY', 'WW']].copy()

In [37]:
flights2['DAY_COUNT'] = 0
flights2.head()

,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,ARRIVAL_DELAY,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,WW,DAY_COUNT
0,4,AS,98,N407AS,ANC,SEA,-22.0,NaN,NaN,NaN,NaN,NaN,1,0
1,4,AA,2336,N3KUAA,LAX,PBI,-9.0,NaN,NaN,NaN,NaN,NaN,1,0
2,4,US,840,N171US,SFO,CLT,5.0,NaN,NaN,NaN,NaN,NaN,1,0
3,4,AA,258,N3HYAA,LAX,MIA,-9.0,NaN,NaN,NaN,NaN,NaN,1,0
4,4,AS,135,N527AS,SEA,ANC,-21.0,NaN,NaN,NaN,NaN,NaN,1,0

In [38]:
import time
tim = time.time()
day = 1
for i,row in flights2.iterrows():
    flights2.set_value(i,'DAY_COUNT',day)
    if flights2.loc[i,'DAY_OF_WEEK'] != flights2.loc[i+1,'DAY_OF_WEEK']:
        day = day + 1
    else:
        continue
print "Time to run code is ", (time.time() - tim)/60, "minutes"

KeyError: 'the label [5714008] is not in the [index]'

In [40]:
flights2.tail()

,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,ARRIVAL_DELAY,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,WW,DAY_COUNT
5714003,4,B6,688,N657JB,LAX,BOS,-26.0,NaN,NaN,NaN,NaN,NaN,53,365
5714004,4,B6,745,N828JB,JFK,PSE,-16.0,NaN,NaN,NaN,NaN,NaN,53,365
5714005,4,B6,1503,N913JB,JFK,SJU,-8.0,NaN,NaN,NaN,NaN,NaN,53,365
5714006,4,B6,333,N527JB,MCO,SJU,-10.0,NaN,NaN,NaN,NaN,NaN,53,365
5714007,4,B6,839,N534JB,JFK,BQN,2.0,NaN,NaN,NaN,NaN,NaN,53,365

In [36]:
import time
tim = time.time()
print "Time to run code is ", time.time() - tim, "seconds"

Time to run code is  0.000453948974609 seconds

In [45]:
import pandas as pd
import numpy as np
flights4 = pd.read_csv('flightsbyWWpart2.csv')
flights4 = pd.DataFrame(flights4)

In [47]:
flights4.tail()

,Unnamed: 0,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,ARRIVAL_DELAY,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY,WW,DAY_COUNT
5714003,5714003,4,B6,688,N657JB,LAX,BOS,-26.0,NaN,NaN,NaN,NaN,NaN,53,365
5714004,5714004,4,B6,745,N828JB,JFK,PSE,-16.0,NaN,NaN,NaN,NaN,NaN,53,365
5714005,5714005,4,B6,1503,N913JB,JFK,SJU,-8.0,NaN,NaN,NaN,NaN,NaN,53,365
5714006,5714006,4,B6,333,N527JB,MCO,SJU,-10.0,NaN,NaN,NaN,NaN,NaN,53,365
5714007,5714007,4,B6,839,N534JB,JFK,BQN,2.0,NaN,NaN,NaN,NaN,NaN,53,365